name: kakao-bot
region: sgp
services:
- name: web
  source_dir: /
  github:
    repo: kkhwan1/kakaoBOT_FI
    branch: main
  dockerfile_path: Dockerfile
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /
  health_check:
    http_path: /health
  envs:
  - key: PORT
    value: "8080"
  - key: PYTHONUNBUFFERED
    value: "1"
